### ISSUE TITLE
Realidade Aumentada

### ISSUE THREAD

**Issue by LSantos06** [ComputerSocietyUNB/UNBQuest#3]
- [X] Importar o _Vuforia_ para o projeto;
- [x] Importar Android SDK para rodar aplicação
- [x] Aprender _Vuforia_;
- [x] Vincular a cena com o _Vuforia_;
- [x] Build;
- [x] Commit branch AR;
- [x] .gitignore.

**Comment by LSantos06** [comment]
https://noperation.wordpress.com/2014/11/09/realidade-aumentada-com-vuforia-em-unity3d-instalacao-e-exemplo-ola-mundo/

**Comment by Dayof** [comment]
Apk 1.1 desta issue : https://developer.cloud.unity3d.com/share/ZJCv5BKiIf/
